import { model, Schema } from "mongoose";

const UserSchema = new Schema(
  {
    FullName: {
      type: String,
      required: true,
    },
    Email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    Password: {
      type: String,
      required: true,
    },
    isAdmin: {
      type: Boolean,
      default: false,
    },
    isActive: {
      type: Boolean,
      default: false,
    },
    isBlocked: {
      type: Boolean,
      default: false,
    },
    OTP: {
      type: Number,
      required: true,
    },
    OTPExpiry: {
      type: Date,
    },
    wishlist: [
      {
        type: Schema.Types.ObjectId,
        ref: "Product",
      },
    ],
    addresses: [
      {
        // _id: false,   this disables auto _id for subdocument
        // _id is automatically generated by MongoDB for each subdocument in the array
        label: {
          type: String,
          required: true,
        },
        addressId: {
          type: Schema.Types.ObjectId,
          ref: "UserAddress",
          required: true,
        },
      },
    ],
    profileImage: {
      type: String,
    },
  },
  { timestamps: true }
);

const User = model("User", UserSchema);

export default User;
